suorganizer/blog/urls.py
from django.conf.urls import url
from . import views

# app_name = 'blog'

urlpatterns=[
    url(r'^$', views.PostList.as_view(), name='blog_post_list'),
    url(r'^create/$', views.PostCreate.as_view(), name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[-\w]+)/$',
        views.post_detail, name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$', views.PostUpdate.as_view(), name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r' (?P<month>\d{1,2})/'
        r' (?P<slug>[\w\-]+)/'
        r'delete/$', views.PostDelete.as_view(), name='blog_post_delete'),
]

suorganizer/organizer/urls.py
from django.conf.urls import url
from . import views

app_name = 'organizer'

urlpatterns =[
    url(r'^tag/create/$', views.TagCreate.as_view(), name= 'organizer_tag_create'),
    url(r'^tag/$', views.Taglist.as_view(), name='organizer_tag_list'),
    # url(r'^((?P<page_number>\d+))?$', views.TagPageList.as_view(), name='organizer_tag_page'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.tag_detail, name='organizer_tag_detail'),
    url(r'^tag/(?P<slug>[-\w]+)/update/$', views.TagUpdate.as_view(), name='organizer_tag_update'),
    url(r'^tag/(?P<slug>[-\w]+)/delete/$', views.TagDelete.as_view(), name='organizer_tag_delete'),
    url(r'^newslink/create/$', views.NewsLinkCreate.as_view(), name='organizer_newslink_create'),
    url(r'^newslink/update/(?P<pk>\d+)/$',views.NewsLinkUpdate.as_view(), name='organizer_newslink_update'),
    url(r'^newslink/delete/(?P<pk>\d+)/$',views.NewsLinkDelete.as_view(), name='organizer_newslink_delete'),
    url(r'^startup/$', views.StartupList.as_view(), name='organizer_startup_list'),
    url(r'^startup/create/$',views.StartupCreate.as_view(), name='organizer_startup_create'),
    url(r'^startup/(?P<slug>[-\w]+)/$', views.startup_detail, name='organizer_startup_detail'),
    url(r'^startup/(?P<slug>[-\w]+)/update/$', views.StartUpUpdate.as_view(), name='organizer_startup_update'),
    url(r'^startup/(?P<slug>[-\w]+)/delete/$', views.StartUpDelete.as_view(), name='organizer_startup_delete'),
]

suorganizer/suorganizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import urls as blog_urls
from contact import urls as contact_urls
from . import views

urlpatterns = [
    url(r'^$',views.redirect_root),
    url(r'^blog/', include(blog_urls)),
    url(r'^',include('organizer.urls', namespace='organizer')),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', admin.site.urls),
]

suorganizer/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

   <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <title>
      {% block title %}
        Startup Organizer
      {% endblock %}

    </title>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog_post_list' %}">Blog List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'organizer:organizer_startup_list' %}">Startup List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'organizer:organizer_tag_list' %}">Tag List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
          </li>
        </ul>
      </div>
    </nav>

    
<div class="container">

  <header>
    <div class="container">


    <div class="jumbotron">
    <center><h1>Startup Organizer</h1></center>
        </div>
            </div>
  </header>



    {% if messages %}
    <div class="">
      <div class="">
        <ul>
          {% for message in messages %}
          {% if message.tags %}
          <li class="{{ message.tags }}"></li>
          {% else %}
          <li>
            {% endif %}
          {{ message }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>
    {% endif %}


  <main>
    {% block content %}
    This is a default content
    {% endblock %}
  </main>

    </div>
<footer>
<p>
&copy;2017
<a href="http://www.google.com"> Sam Ghadri</a>
</p>
<p>
Created for
<a href="http://www.github.com"> Sam Django Solutions</a>
</p>
</footer>

  </body>


</html>