suorganizer/blog/urls.py
from django.conf.urls import url
from . import views

# app_name = 'blog'

urlpatterns=[
    url(r'^$', views.PostList.as_view(), name='blog_post_list'),
    url(r'^create/$', views.PostCreate.as_view(), name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[-\w]+)/$',
        views.post_detail, name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$', views.PostUpdate.as_view(), name='blog_post_update'),
    url(r'^(?P<year>\d{4})/'
        r' (?P<month>\d{1,2})/'
        r' (?P<slug>[\w\-]+)/'
        r'delete/$', views.PostDelete.as_view(), name='blog_post_delete'),
]

suorganizer/organizer/urls.py
from django.conf.urls import url
from . import views

app_name = 'organizer'

urlpatterns =[
    url(r'^tag/create/$', views.TagCreate.as_view(), name= 'organizer_tag_create'),
    url(r'^tag/$', views.Taglist.as_view(), name='organizer_tag_list'),
    # url(r'^((?P<page_number>\d+))?$', views.TagPageList.as_view(), name='organizer_tag_page'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.tag_detail, name='organizer_tag_detail'),
    url(r'^tag/(?P<slug>[-\w]+)/update/$', views.TagUpdate.as_view(), name='organizer_tag_update'),
    url(r'^tag/(?P<slug>[-\w]+)/delete/$', views.TagDelete.as_view(), name='organizer_tag_delete'),
    url(r'^newslink/create/$', views.NewsLinkCreate.as_view(), name='organizer_newslink_create'),
    url(r'^newslink/update/(?P<pk>\d+)/$',views.NewsLinkUpdate.as_view(), name='organizer_newslink_update'),
    url(r'^newslink/delete/(?P<pk>\d+)/$',views.NewsLinkDelete.as_view(), name='organizer_newslink_delete'),
    url(r'^startup/$', views.StartupList.as_view(), name='organizer_startup_list'),
    url(r'^startup/create/$',views.StartupCreate.as_view(), name='organizer_startup_create'),
    url(r'^startup/(?P<slug>[-\w]+)/$', views.startup_detail, name='organizer_startup_detail'),
    url(r'^startup/(?P<slug>[-\w]+)/update/$', views.StartUpUpdate.as_view(), name='organizer_startup_update'),
    url(r'^startup/(?P<slug>[-\w]+)/delete/$', views.StartUpDelete.as_view(), name='organizer_startup_delete'),
]

suorganizer/suorganizer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog import urls as blog_urls
from contact import urls as contact_urls
from . import views

urlpatterns = [
    url(r'^$',views.redirect_root),
    url(r'^blog/', include(blog_urls)),
    url(r'^',include('organizer.urls', namespace='organizer')),
    url(r'^contact/', include(contact_urls)),
    url(r'^admin/', admin.site.urls),
]

suorganizer/organizer/models.py
from django.db import models
from django.core.urlresolvers import reverse
# from blog.models import Post

class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)
    slug = models.SlugField(max_length=40,
                            unique=True,
                            help_text='A label for URL config')

    def __str__(self):
        return self.name.title()

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('organizer:organizer_tag_detail',
                        kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('organizer:organizer_tag_update', kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer:organizer_tag_delete', kwargs={'slug':self.slug})


class StartUp(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(unique=True,
                            help_text='A label for URL config')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag)


    def __str__(self):
        return self.name


    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'
        verbose_name_plural = "Startups"



    def get_absolute_url(self):
        return reverse('organizer:organizer_startup_detail',
                        kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('organizer:organizer_startup_update', kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('organizer:organizer_startup_delete', kwargs={'slug':self.slug})


class NewsLink(models.Model):
    title = models.CharField(max_length=70)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(StartUp)


    def __str__(self):
        return '{}:{}'.format(self.startup, self.title)

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'


    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_update_url(self):
        return reverse('organizer:organizer_newslink_update', kwargs={'pk':self.pk})

    def get_delete_url(self):
        return reverse('organizer:organizer_newslink_delete', kwargs={'pk':self.pk})

suorganizer/organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Tag, NewsLink, StartUp



class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'


class SlugCleanMixin:

    def clean_slug(self):
        new_slug =(self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError('The Slug can not be create!!')
        return new_slug



class StartUpForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = StartUp
        fields = '__all__'



class TagForm(SlugCleanMixin, forms.ModelForm):
    # name = forms.CharField(max_length=40)
    # slug = forms.SlugField(max_length=40, help_text='A label for URL config')
    class Meta:
        model = Tag
        fields = "__all__"
                    # ['name', 'slug']
        # exclude = tuple() For the mdoel instances you want to exclude from __all__ forms

    def clean_name(self):
        return self.cleaned_data['name'].lower()

    def save(self):
        new_tag = Tag.objects.create(
            name=self.cleaned_data['name'],
            slug=self.cleaned_data['slug'])
        return new_tag

suorganizer/organizer/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.core.urlresolvers import reverse_lazy
from .models import Tag, StartUp, NewsLink
from .forms import TagForm, StartUpForm, NewsLinkForm
from django.views.generic import View
from .utils import ObjectCreateMixin, ObjectUpdateMixin, ObjectDeleteMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# from django.http.response import HttpResponse
# from django.template import loader, RequestContext


class Taglist(View):
    page_kwarg = 'page'
    template_name = 'organizer/tag_list.html'
    paginate_by = 5

    def get(self, request):
        tags = Tag.objects.all()
        paginator = Paginator(tags,
                            self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)

        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_kwarg,
                        n=page.previous_page_number())
        else:
            prev_url = None

        if page.has_next():
            next_url = '?{pkw}={n}'.format(pkw=self.page_kwarg,
                        n=page.next_page_number())
        else:
            next_url = None

        context = {
            "is_paginated": page.has_other_pages(),
            "next_page_url": next_url,
            "paginator": paginator,
            "previous_page_url": prev_url,
            'tag_list': page}

        return render(request, self.template_name, context)
# def tag_list(request):
#     return render(request, 'organizer/tag_list.html',
#                         {'tag_list': Tag.objects.all()})
    # tag_list = Tag.objects.all()
    # template = loader.get_template('organizer/tag_list.html')
    # context = RequestContext(request,{'tag_list': tag_list})
    # output = template.render(context)
    # return HttpResponse(output)

# def tag_create(request):
#     if request.method == 'POST':
#         form = TagForm(request.POST)
#         if form.is_valid():
#             new_tag = form.save()
#             new_tag.save()
#             return redirect(new_tag)
#         else:
#             form = TagForm()
#         return render(request, 'organizer/tag_form.html', {'form':form})

class TagCreate(ObjectCreateMixin,View):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'

    # def get(self, request):
    #     return render(request, self.template_name, {'form':self.form_class()})
    #
    # def post(self, request):
    #     bound_form = self.form_class(request.POST)
    #     if bound_form.is_valid():
    #         new_tag = bound_form.save()
    #         return redirect(new_tag)
    #     else:
    #         return render(request, self.template_name,{'form':bound_form})

def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request,'organizer/tag_detail.html', {'tag':tag})
    # template = loader.get_template('organizer/tag_detail.html')
    # context = {'tag': tag}
    # return HttpResponse(template.render(context))


class TagUpdate(ObjectUpdateMixin, View):
    form_class = TagForm
    model = Tag
    template_name = 'organizer/tag_form_update.html'


class TagDelete(ObjectDeleteMixin, View):
    model = Tag
    success_url = reverse_lazy('organizer:organizer_tag_list')
    template_name = 'organizer/tag_confirm_delete.html'


class StartupList(View):
    page_kwarg = 'page'
    paginate_by  = 1 #items per page
    template_name = 'organizer/startup_list.html'

    def get(self, request):
        startups = StartUp.objects.all()
        paginator = Paginator(startups, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)

        if page.has_previous():
            prev_url = "?{pkw}={n}".format(pkw=self.page_kwarg,
                        n=page.previous_page_number())
        else:
            prev_url = None

        if page.has_next():
            next_url = '?{pkw}={n}'.format(pkw=self.page_kwarg,
                        n=page.next_page_number())
        else:
            next_url = None
        context = {'is_paginated': page.has_other_pages(),
                   'next_page_url': next_url,
                   'paginator': paginator,
                   'previous_page_url': prev_url,
                   'startup_list': page}
        return render(request, self.template_name, context)


class StartupCreate(ObjectCreateMixin, View):

    form_class = StartUpForm
    template_name = 'organizer/startup_form.html'

    # def get(self, request):
    #     return render(request, self.template_name,{'form':self.form_class()})
    #
    # def post(self, request):
    #     bound_form = self.form_class(request.POST)
    #     if bound_form.is_valid():
    #         new_startup =  bound_form.save()
    #         return redirect(new_startup)
    #     else:
    #         return render(request, self.template_name, {'form':bound_form})

class StartUpUpdate(ObjectUpdateMixin, View):
    form_class = StartUpForm
    model = StartUp
    template_name = 'organizer/startup_form_update.html'

def startup_detail(request, slug):
    startup = get_object_or_404(StartUp, slug__iexact=slug)
    return render(request, 'organizer/startup_detail.html',
                            {'startup':startup})

class StartUpDelete(ObjectDeleteMixin, View):
    model = StartUp
    success_url = reverse_lazy('organizer:organizer_startup_list')
    template_name = 'organizer/startup_confirm_delete.html'

class NewsLinkCreate(ObjectCreateMixin, View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form.html'

    # def get(self, request):
    #     return render(request, self.template_name,{'form':self.form_class()})
    #
    # def post(self, request):
    #     bound_form = self.form_class(request.POST)
    #     if bound_form.is_valid():
    #         new_newslink = bound_form.save()
    #         return redirect(new_newslink)
    #     else:
    #         return render(request, self.template_name, {'form':bound_form})


class NewsLinkUpdate(View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form_update.html'

    def get(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        context = {'form':self.form_class(instance=newslink), 'newslink':newslink}
        return render(request, self.template_name, context )

    def post(self, request, pk):
        newslink = get_object_or_404(NewsLink,pk=pk)
        bound_form = self.form_class(request.POST,instance=newslink)
        if bound_form.is_valid():
            new_newslink = bound_form.save()
            return redirect(new_newslink)
        else:
            context = {'form':bound_form,'newslink':newslink}
            return render(request,self.template_name, context)

class NewsLinkDelete(View):
    def get(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        return render(request, 'organizer/newslink_confirm_delete.html')

    def post(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        startup = newslink.startup.delete()
        return redirect(startup)

suorganizer/organizer/templates/organizer/base_organizer.html
{% extends "base.html" %}

suorganizer/organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Article
{% endblock %}

{% block content %}

<div class="container">
  <div>
    <form action="{{ newslink.get_delete_url }}" method="POST">
      {% csrf_token %}
      <p>Are you sure you want to Delete {{ newslink.name }}? </p>
      <a href="{{ newslink.get_absolute_url }}">Cancel</a>
      <button type="submit">Delete article</button>
    </form>
  </div>
</div>


{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{ block.super }} - Link Newslink to Startup
{% endblock %}

{% block content %}

<div class="container">
  <div class="#">
<form action="{% url 'organizer:organizer_newslink_create' %}" method="POST">
  {% csrf_token %}
{{ form.as_p }}

<button type="submit">Link Article</button>

</form>
</div>

</div>

{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Your Article
{% endblock %}
{% block content %}

<div class="container">
  <div class="#">

    <form  action="{{ newslink.get_update_url }}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update Article</button>

    </form>

  </div>

</div>

{% endblock %}

suorganizer/organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Startup
{% endblock %}

{% block content %}

<div class="container">
  <div>
    <form action="{{ startup.get_delete_url }}" method="POST">
      {% csrf_token %}
      <p>Are you sure you want to Delete {{ startup.name }}? </p>
      <a href="{{ startup.get_absolute_url }}">Cancel</a>
      <button type="submit">Delete StartUp</button>
    </form>
  </div>
</div>


{% endblock %}

suorganizer/organizer/templates/organizer/startup_detail.html
<article class="">

<h2>{{ startup.name }}</h2>
<dl>
  <dt>Date founded</dt>
  <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
  <dt>Website</dt>
  <dd>{{ startup.website|urlize }}</dd>
  <dt> Contact</dt>
  <dd>{{startup.contact}}</dd>

  <dt>Tag{{startup.tags.count|pluralize }}</dt>
  <ul>
  <li>
    <a href="{{ startup.get_update_url }}">Edit Startup</a>
  </li>
  <li>
    <a href="{{ startup.get_delete_url }}">Delete Startup</a>
  </li>
  </ul>
  {% for tag in startup.tags.all %}
  <dd>
    <a href="{{ tag.get_absolute_url }}">{{tag.name|title}}
    </a>
  </dd>

  {% endfor %}
</dl>

{{ startup.description|linebreaks }}
{% if startup.newslink_set.all %}
<section>
  <h3>Recent News</h3>
<ul>
  {% for newslink in startup.newslink_set.all %}
  <li>
    <a href="{{ newslink.link }}"> {{newslink.title|title}}</a>
  </li>
  <ul>
  <li>
    <a href="{{ newslink.get_update_url }}">Edit Article</a>
  </li>
</ul>
  {% endfor %}
</ul>

</section>
{% endif %}
<p>
<a href="{% url 'organizer:organizer_newslink_create' %}">Add Article</a>
</p>


{% if startup.blog_posts.all %}
<section>
  <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
<ul>
  {% for post in startup.blog_posts.all  %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a>
  </li>

  {% endfor %}
</ul>
</section>
{% endif %}

</article>

suorganizer/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startup Form

{% endblock %}

{% block content %}

<div class="container">
  <div>
    <form action="{% url 'organizer:organizer_startup_create' %}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type='submit'>Create Startup</button>
    </form>
  </div>
</div>

{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Your Startup Details
{% endblock %}
{% block content %}

<div class="container">
  <div class="#">

    <form  action="{{ startup.get_update_url }}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update Now</button>

    </form>

  </div>

</div>

{% endblock %}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
<div>
  <a href="{% url 'organizer:organizer_startup_create' %}"> Create a Startup</a>
</div>
<h2>Startup List </h2>

<ul>
  {% for startup in startup_list  %}
  <li>
    <a href="{{ startup.get_absolute_url }}">{{ startup.name }}</a>
  </li>

  <ul>
  <li>
    <a href="{{ startup.get_update_url }}">Edit Startup</a>
  </li>
  </ul>

    {% empty %}
    <li>
      <em>There are No Startup Yet!!</em>
    </li>
    <ul>
    <li>
      <a href="{{ newslink.get_update_url }}">Edit Article</a>
    </li>
  </ul>
  {% endfor %}
</ul>

{% if is_paginated %}
<ul>

{% if previous_page_url %}
<li>
<a href="{{ previous_page_url }}">Previous</a>
</li>
{% endif %}
<li>
Page {{ startup_list.number }}
of {{ paginator.num_pages }}
</li>
{% if next_page_url %}
<li>
<a href="{{ next_page_url }}">Next</a>
</li>
{% endif %}
</ul>

{% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}

<div class="container">
  <div>
    <form action="{{ tag.get_delete_url }}" method="POST">
      {% csrf_token %}
      <p>Are you sure you want to Delete {{ tag.name }}? </p>
      <a href="{{ tag.get_absolute_url }}">Cancel</a>
      <button type="submit">Delete Tag</button>



    </form>



  </div>

</div>


{% endblock %}

suorganizer/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{block.super}} - {{tag.name|title}}
{% endblock %}

{% block content %}

<h2> {{ tag.name|title }} </h2>
<ul>
<li>
  <a href="{{ tag.get_update_url }}">Edit Tag</a>
</li>
<li>
  <a href="{{ tag.get_delete_url }}">Delete Tag</a>
</li>
</ul>
{% if tag.startup_set.all %}
<section>

<h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
<p>This Tag is associated with
  {{tag.startup_set.count}}
  Startup{{ tag.startup_set.count|pluralize }}
</p>

<ul>
{% for startup in tag.startup_set.all %}
<li><a href="{{ startup.get_absolute_url }}">
  {{ startup.name }}
</a></li>

{% endfor %}
</ul>
</section>
{% else %}
<p>Sorry! this Tag is Not associated with any startup!!</p>
{% endif %}

{% if tag.blog_posts.all %}
<section>
  <h3>Blog Post{{ tag.blog_posts.count|pluralize}}</h3>
  <ul>
      {% for post in tag.blog_posts.all %}
      <li>
        <a href="{{ post.get_absolute_url }}">
          {{ post.title|title }}
        </a>
      </li>
      {% endfor %}
  </ul>
</section>
{% endif %}

{% if not tag.startup_set.all and not tag.blog_posts.all %}
<p>Sorry this Tag is not associated with any content </p>

{% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}

<div class="container">
  <div class="#">
<form action="{% url 'organizer:organizer_tag_create' %}" method="POST">
  {% csrf_token %}
{{ form.as_p }}

<button type="submit">Create Tag</button>

</form>
</div>

</div>

{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}
{% block content %}

<div class="container">
  <div class="#">

    <form  action="{{ tag.get_update_url }}" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update Tag</button>

    </form>

  </div>

</div>

{% endblock %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends "organizer/base_organizer.html" %}
{% block title %}
{{ block.super }} - Tag list
{% endblock %}

{% block content %}


<center><h2><span class="badge badge-secondary">Tag List</span></h2></center>

<ul>
  {% for tag in tag_list %}
  <div class="col-lg-3 col-md-6 cold-sm-12">
  <li class="card">
    <a class="card-header" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
    <div class="container">
      <a class='btn btn-warning' href="{{ tag.get_update_url }}">Edit</a>
      <a class='btn btn-danger' href="{{ tag.get_delete_url }}">Delete</a>
  </li>

  </div>
    {% empty %}
    <li>
      <em>There are No TAG Yet!!</em>
    </li>
  {% endfor %}
</ul>
</div>

<div>
  <a href="{% url 'organizer:organizer_tag_create' %}"> Create a Tag</a>
</div>


{% if is_paginated %}
<ul>
  {% if previous_page_url %}
  <li>
    <a href="{{ previous_page_url }}">Previous</a>
  </li>
  {% endif %}
  <li>
  Page {{ tag_list.number }}
  of {{ paginator.num_pages }}
  </li>
  {% if next_page_url %}
  <li>
    <a href="{{ next_page_url }}">Next</a>
  </li>
  {% endif %}
</ul>
{% endif %}



{% endblock %}